name: RFCs CI
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [rfcs]
  workflow_dispatch:
jobs:
  release:
    name: Update API and files
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update RFCs
        uses: koj-co/rfcs-action@HEAD
        with:
          token: "${{ secrets.GH_PAT }}"
